# Exclude paths and files during build project
exclude: [
  "node_modules",
  "img/src-sprite",
  "js/app.js",
  "js/smooth-scroll.js",
  "js/echo.js",
  "Gruntfile.js",
  "package.json",
  "readme.md"
]

# Site settings
title: Maternidades Manaus
email: falecom@maternidadesmanaus.com.br
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maternidadesmanaus.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Social network
social_networks:
  -
    name: "instagram"
    link: "https://instagram.com/maternidadesmanaus/"
    class: "ig"
  -
    name: "google+"
    link: "https://plus.google.com/107723451370774227293"
    class: "go"
  -
    name: "facebook"
    link: "https://www.facebook.com/maternidadesmanaus/"
    class: "fb"

social_sharer:
  twitter: "https://twitter.com/intent/tweet?ref_src=twsrc%5Etfw&text=Ajude%20a%20avaliar%20as%20maternidades%20da%20cidade%20de%20Manuas%20%7C&tw_p=tweetbutton&url=https%3A%2F%2Fmaternidadesmanaus.com.br%2F"
  facebook: "https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fmaternidadesmanaus.com.br%2F%23.VcJQC3C30X8.facebook"
  google_plus: "https://plus.google.com/share?url=http%3A%2F%2Fmaternidadesmanaus.com.br%2F%23.VcJQSHDZK2c.google_plusone_share&t=Maternidades+Manaus"